---
- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
      - name: Distribution
        debug: msg="{{ ansible_distribution }}"
      - name: Distribution Version
        debug: msg="{{ ansible_distribution_version }}"
      - name: Distribution Major Version
        debug: msg="{{ ansible_distribution_major_version }}"
