---
- name: Adding Repo Shutter
  apt_repository:
    repo: 'ppa:linuxuprising/shutter'
    validate_certs: yes
    update_cache: no
    state: present

- name: Install Shutter
  apt:
      name: shutter
      state: latest
