---

- name: Get Zoom Deb
  become: yes
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom_amd64.deb

- name: Install prerequisition library for Zoom
  apt:
    name: {{ zoom.ZOOM_PACKAGES }}
    state: present
    force_apt_get: "yes"

- name: Install Zoom
  apt:
    deb: /tmp/zoom_amd64.deb
