---

- name: Get Zoom Deb
  become: yes
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom_amd64.deb

- name: Install prerequisition library for Zoom
  apt:
    name: libxcb-xtest0

- name: Install Zoom
  apt:
    deb: {{ item }}
  with_items:
    - /tmp/zoom_amd64.deb
  sudo: yes
