---

- name: Add Google Chrome Key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Get Chrome Deb
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main owner=root group=root mode=644
    state: present

- name: Update apt after adding Google Chrome
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
