---

- name: Add Google Chrome Key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Get Chrome Deb
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main owner=root group=root mode=644
    validate_certs: true
    update_cache: no
    state: present

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
