---

- name: Skype GPG Key
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY

- name: Get Skype
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    filename: skype-deb

- name: Install Skype
  apt:
    name: skype-deb
