---
- name: Get Skype Deb
  become: yes
  get_url:
    url: https://go.skype.com/skypeforlinux-64.deb
    dest: /tmp/skypeforlinux-64.deb

- name: Install Skype
  apt:
    deb: /tmp/skypeforlinux-64.deb
